# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpotifyITunes' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    pod 'SwiftyJSON', '~> 4.0'
    pod 'Alamofire', '~> 5.0.0-rc.2'
    pod 'SDWebImage'
    pod 'IQKeyboardManagerSwift'

  # Pods for SpotifyITunes

  target 'SpotifyITunesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SpotifyITunesUITests' do
    # Pods for testing
  end

end
